export const appConfig = {
  SOUND_API_URL: import.meta.env.VITE_SOUND_API_URL,
  SOUND_ACCESS_KEY: import.meta.env.VITE_SOUND_ACCESS_KEY,
  API_URL: import.meta.env.VITE_API_URL,
  IMAGE_URL: import.meta.env.VITE_APP_IMAGE_URL,
  WEB_URL: import.meta.env.VITE_APP_WEB_URL,
  SOCKET_URL: import.meta.env.VITE_APP_SOCKET_URL,
  ENCRYPTION_SECRET_KEY: import.meta.env.VITE_APP_ENCRYPTION_SECRET_KEY,
  ENCRYPTION_MESSAGE: import.meta.env.VITE_APP_ENCRYPTION_MESSAGE,
  FB_APP_ID: import.meta.env.VITE_APP_FB_APP_ID,
  GOOGLE_CLIENT_ID: import.meta.env.VITE_APP_GOOGLE_CLIENT_ID,
  STRIPE_PUBLIC_KEY: import.meta.env.VITE_APP_STRIPE_PUBLIC_KEY,
  STRIPE_SECRET_KEY: import.meta.env.VITE_APP_STRIPE_SECRET_KEY,
};
